### ISSUE TITLE
SB3 Doc

### ISSUE THREAD

**Issue by araffin** [jmacglashan/decisions_and_dragons#3]
Hello @jmacglashan ,

before I forget, could you please add a link to your website in the resource section of SB3?

https://stable-baselines3.readthedocs.io/en/master/guide/rl.html

Thanks =)

**Comment by jmacglashan** [comment]
I'd be happy to. I made a PR [here](https://github.com/DLR-RM/stable-baselines3/pull/2044)

**Comment by araffin** [comment]
merci !
